name: Earthly Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Earthly
        uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.8.6
      
      - name: Build Docker image with Earthly
        run: earthly --ci +ns-image

      - name: List Docker images
        run: docker images ls
      
      - name: Save Docker image as tarball
        run: docker save -o northstar.tar rickyegl/northstar:latest
          
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: my-docker-image.tar
