name: Earthly Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Earthly
        uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.8.6
      
      - name: Docker Login
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      
      - name: Build and push Docker image with Earthly
        run: |
          earthly --ci --push +image
